---
- name: Converge
  hosts: all

  vars:
    epel_repo_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    epel_repo_gpg_key_url: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    epel_repofile_path: "/etc/yum.repos.d/epel.repo"

  pre_tasks:

    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: 1.Check if EPEL repo is already configured.
      stat: path={{ epel_repofile_path }}
      register: epel_repofile_result

    - name: 2.Install EPEL repo.
      yum:
        name: "{{ epel_repo_url }}"
        state: present
      register: result
      when: not epel_repofile_result.stat.exists

    - name: 3.Import EPEL GPG key.
      rpm_key:
        key: "{{ epel_repo_gpg_key_url }}"
        state: present
      when: not epel_repofile_result.stat.exists


    - name: Install python-pip
      yum:
        name: 'python-pip'
        state: latest

    - name: Upgrade pip
      shell: pip install --upgrade pip

    - name: Install AWS CLI with pip
      pip:
        name: 'awscli'
        state: latest

    - name: Install boto with pip
      pip:
        name: 'boto'
        state: latest

  roles:
    - role: first-test
